development: &common
  adapter: postgresql
  sequel_adapter: postgres
  encoding: utf8
  reconnect: false
  database:
  pool: 5
  username:
  password:
  host: localhost

test:
  <<: *common
  database:

# Matching environments specified in this file will override the above.
<%= IO.read('config/database.local.yml') if File.exists?('config/database.local.yml') %>
